### ISSUE TITLE
Создание алгоритма генерации маршрута

### ISSUE THREAD

**Issue by elinnka** [zhabalyak/IT-Project-ComfyTravel#10]
доброе утро надеюсь я ничего не сломала можно я вкину сюда свои вопросы
больше всего меня волнуетб что можно вытащить из карт в приложуху? типа оттуда можно будет получить маршрут с остановочками или нужно это все как то отдельное вручную считать?
это наверное к @IgelSchnauze да

а еще нам же нужно все сделать максимально просто да? можно просто у каждой достопримечтальности будет какой то счет, к которому мы что то будем добавлять за полное/частичное совпадение с тем что хочет пользователь и в конце чисто отсортируем по этому счету и будем перебирать максимально подходящие до тех пор пока время маршрута не совпадет с требуемым временем?)))))

**Comment by elinnka** [comment]
Приятного чтения ;)

короче я не совсем понимаю с какой стороны подступиться))) и страшно думать о реализации поэтому пока супер примерно вот как то так:

У нас есть список всех всех мест, какие то обязательные точки, минимальный возраст детей, выбран обязон один способ передвижения, желаемые типы мест (музеи парки тыры пыры), выбрано во сколько планируется начаться маршрут и сколько он продлится по времени

1. сначала строится список всех мест, это типа будет список предпочтений
2. в самое начало ставятся обязательные к посещению места (мб можно в отдельный список)
3. сразу из списка удаляются все места которые не проходят по возрасту (типа условно если у какого то музея  в картах 18+ а у нас дети то мы выкидываем)
4. можно отсортировать прошедшие 3 пункт места по возрасту из карт или просто мы сами пропишем типа если есть дети то театры лучше в конец а кино в начало хз чисто по приколу можно чтобы использовать тот факт что есть дети
5. потом сортировка по желаемым местам. То есть если сначала все шло в каком то рандомном порядке, и чел выбрал что хочет в парки то теперь список условно выглядит так: [обязательные к посещению][парки][памятники][музей]. так как типов немного то можно просто прописать всевозможные варианты которые выберет чел и как в таком случае сортировать)))) надеюс понятно
6. отсекаются те места для которых рано/поздно (если время начала прогулки 17 30 то отсекаем музеи и тд)

и еще в какой то момент времени можно отсортировать по отзывам из карт типа

а вот дальше я не особо придумала потому что там уже вопросы насчет того откуда брать маршрут между точками но
было бы прикольно применить какую нибудь штуку с графов типа у нас есть точки и мы должны построить между ними кратчайший маршрут?
то есть тут уже задача попроще, у нас есть сколько то обязательных точек и отсортированный список других точек. и в теории между всеми точками можно получить расстояние. и наложить на это все временные рамки))

так что вот моменты на которые нужно обратить внимание:
1) будут ли еще параметры 
2) как получать путь между точками из карт
3) как строить кратчайшие маршруты
4) как рассчитывать время (то есть просто время пути + условные 30 минут в парке, час в музее, 3 часа в театре и еще какие нибудь погрешности?)
5) можете полностью поменять алгоритм если у вас будут норм идеи ахахаха

**Comment by KMn04** [comment]
Идея со счётом мне кажется хорошей, я за

Про поиск минимального пути плюсую, но тк это связано с картами, вопрос к Вике

В целом пока что идей лучше у меня неть, 1/2/3 как будто к Вике вопросы(?), насчёт 4го мне кажется норм что
парки 30мин, театр 3ч, кино 2ч, музей 1ч, но мне кажется везде где покупаются билеты можно закладывать +15 минут

**Comment by KMn04** [comment]
а есть 3 вопрос это не про карты, а про как мы будем выбирать вес, то мне кажется надо сначала построить логичный маршрут по обязательным точкам (это может быть не остов, но назовём это остов в значении что это штука обязательная), а потом к ней какие можно ещё точки прикрутить, те крутим

мне в голову  ничего кроме какого-то соотношения не приходит, а соотношении будут участвовать время на дорогу/расстояние + приоритет + что-нибудь ещё, может оценка заведения

**Comment by IgelSchnauze** [comment]
Такс
Мне в принципе тоже понравилось то, что ты предлагаешь
Идею со счетом я не совсем поняла, но такая формализация точно будет удобна и в этом есть смысл

Единственное что, я боюсь, что могут возникнуть проблемы с недостатком точек для посещения. Например, времени вагон, а по выбранным параметрам точек там на 2 часа. Но это могу предложить компенсировать перемешкой с другими, других вариантов не вижу

1.  Мне кажется, пока нужно остановиться на этих (значит мне в бд нужно добавить про детишек аля да/нет и все)
2. + 3.  Там просто указываешь точки и способ передвижения (пешком/машины), и кратчайший маршрут так или иначе сам подберется адекватный (а не просто полоска по диагонали). Из него вроде даже можно достать километраж и время пути, но я не пробовала доставать, а только на карте их вижу
4. Да, мне кажется так. Только брать все с большим запасом лучше (насчет билетов и театров в обсуждении бд напишу)

**Comment by zhabalyak** [comment]
Глупый вопрос, а этот алгоритм, который нам нужен, не похож на задачу коммивояжёра?

**Comment by zhabalyak** [comment]
ВОт я подумала, что удобный, это как раз тот, который типа с меньшими перебежками между точками) чтобы через город туда сюда не бегать)

**Comment by elinnka** [comment]
девачки а нет пока никакого примера как вы передаете куда то достопримечательности/параметры от пользователя? если есть то где?(

**Comment by IgelSchnauze** [comment]
От пользователя вряд ли, это мы вчера на словах обсуждали только еще...
