### ISSUE TITLE
Создание HTML-шаблонов для страниц сайта

### ISSUE THREAD

**Issue by KMn04** [zhabalyak/IT-Project-ComfyTravel#11]
Вёрстка начата, но пока супер минимальная, на следующей неделе скину, когда станет покрасивее

**Comment by KMn04** [comment]
Закончить вёрстку, добавить карты, написать и добавить сценарии

**Comment by zhabalyak** [comment]
СПрошу тут, наверное, а где и когды можно будет посмотреть на все вьюшные файлы? А так, как я планировала, я нашла способы передавать данные с вьюшки в контроллер и обратно. Поэтому, мне хотелось бы посмотреть на уже вот существующие файлы и прикинуть в голове, как оно будет фурычить

**Comment by KMn04** [comment]
Завтра утречком/сегодня ночечкой кину
Уточню, что сдам 4 вьюшки (1 для гостя - просто карта, 3 для пользователя авторизованного - та же карта, профиль, архив маршрутов
Другие 4 вьюшки относились к админу, которого, как понимаю, допиливать мы будет позже по мере возможностей
