### ISSUE TITLE
Тестовый вариант связки между веб, бд, картой

### ISSUE THREAD

**Issue by IgelSchnauze** [zhabalyak/IT-Project-ComfyTravel#12]
Мне кажется, нам будет что обсудить здесь

**Comment by IgelSchnauze** [comment]
Свои файлики я вчера закинула в новую ветку, в отдельную там папочку

**Comment by KMn04** [comment]
Я никогда не связывала веб файлы через гит, попробую завтра сначала в тупую (скачать/скопировать себе), если всё будет работать, то уже по-человечески сделаю

**Comment by IgelSchnauze** [comment]
Ой, мне кажется, что через гит не стоит париться, на самом деле
Я просто тебе потом идентичный файлик скину, и заменим этот тестовый на тот нормальный
