### ISSUE TITLE
Добавить в каком-либо формате уже готовые файлы

### ISSUE THREAD

**Issue by zhabalyak** [zhabalyak/IT-Project-ComfyTravel#2]

**Comment by IgelSchnauze** [comment]
Отчитываюсь: папка для отчетов создана, первый отчет уже там

**Comment by zhabalyak** [comment]
@elinnka , ты можешь экспортировать диаграмму как пнг? если можешь, то я попросила бы тебя загрузить её. Я попробовала конвертировать, но качество умерло

**Comment by KMn04** [comment]
раз ишью закрыли то Лада уже увидела, но я просто хотела написать сюда:
