### ISSUE TITLE
Создание и добавление диаграммы последовательностей

### ISSUE THREAD

**Issue by zhabalyak** [zhabalyak/IT-Project-ComfyTravel#4]
Составить диаграмму последовательностей, выложить в папку с диаграммами, возможно краткое сопроводительное описание, дабы сокомандники смогли понять почти сразу.

**Comment by elinnka** [comment]
блнб а в диаграмме должен в каком то виде быть показан сам алгоритм генерации маршрута?.. просто у нас же его нет... 

а еще у нас есть/будет какой то список какие будут параметры и сами достопримечательности?
