### ISSUE TITLE
Определить стек технологий и распределить роли

### ISSUE THREAD

**Issue by KMn04** [zhabalyak/IT-Project-ComfyTravel#6]
Пока очевидно лишь то, что Айсылу делает шифрование, а Вика карты
а остальные 4 пункта пока висят со знаком вопроса
-БД
-алгоритмы 
-сервер
-фронт

**Comment by elinnka** [comment]
все еще не понимаю, почему алгоритмы отдельный пункт если это просто одна функция и немного времени на подумать
(и где обсуждать все это деление, туть?)

**Comment by zhabalyak** [comment]
Ну, я вот так сразу алгоритм подбора маршрута не могу придумать, поэтому, думаю, нужно отдельно посидеть и подумать над этим. И обсуждения можно вести тут, не вижу ничего плохого в этом
