### ISSUE TITLE
Сбор данных для БД 

### ISSUE THREAD

**Issue by IgelSchnauze** [zhabalyak/IT-Project-ComfyTravel#9]
Единственное в чем вопросик еще есть - какие именно данные нужно собирать
Так как у нас есть классификация объектов по музеям, паркам и тд, то возможно было бы удобнее заносить их сразу в бд, чтобы потом с внешними ключами не возиться

**Comment by IgelSchnauze** [comment]
Что имею пока: 96 объектов, среди которых 4 класса - парки, бульвары, музеи, памятники. Данные об объекте из предыдущего пункта

1. Театры наверное глупо добавлять, как и кино, что еще можно туда и нужно ли?
2. Какие данные еще нужны об объектах? Мб пометки о том, подходит/не подходит для детей? Музеи кстати фактически все до 18:00 работают, что удобно для нас

**Comment by zhabalyak** [comment]
Молодец, @IgelSchnauze!

1. А почему глупо добавлять? Мб просто как место развлечения, которое объединит и театр, и кино, и балет, и всякая другая фигня, но это если у тебя останется время и желание.
2. Раз мы отмечали в тз, что там есть типа про детей, то можно добавить пункт про детей, если недолго менять.
3. Мб через 2 часа сообщу)

**Comment by KMn04** [comment]
Ну, время работы и оценка пользователей, видимо, будет сразу на яндекс картах отображаться. 

Правда я не совсем понимаю, как мы по некоторым параметрам, которые есть только на яндекс картах, будем фильтровать то, что есть у нас в БД, это что-то встроенное в карты есть? Или это ложится на серверную часть всяких запросов? Например, какая-то хотя бы краткая информация об объекте (у нас в ТЗ указано "информация об объекте"), да и в целом фильтрация по параметрам.

Надо придумать, как мы будем хранить и выводить самые популярные маршруты. Типа это отдельный списочек, который мы будем парсить на страницу, или это каждый раз запрос к бд? Второе мне больше нравится, тк актуальность как будто будет лучше прослеживаться, но я пока не понимаю, к какой части бд будет обращаться запрос.

Что ещё можно хранить:
-объект маршрут, у которого будет массив точек и время прохождения?
-объект пользователь, у которого будут личные данные, массив маршрутов и анкета с предпочтениями?
-как будто анкета это тоже отдельный объект, который хранит вектор предпочтений 
-запросы и жалобы пользователей надо тоже куда-то прикрутить

Извините, я очень не хочу никого грузить лишней работой с этим проектом, просто я пока не понимаю, откуда мы будем брать эти данные и куда складывать :с

**Comment by IgelSchnauze** [comment]
Сначала ответ Ладе:

1. Кино вот мооожно еще, а вот с театром странно - туда билеты нужно оч сильно заранее ведь покупать, ну и спектакли идут не как кино, не каждый день и не в практически любое время. То есть с театром это прям совсем бесполезно, на мой взгляд
2. Да, добавлю такой параметр
3. Этим займусь после детей и кино

**Comment by IgelSchnauze** [comment]
Время работы и оценка пользователей - это не получится достать из их данных, только если свои писать/собирать, чем мы заниматься конечно же не будем

Вот в этом и прикол, что мы работать можем только со своими данными, я даже насчет километража и времени пути пока не знаю, можно ли их вообще достать как-то в прогу. Насчет инфы об объекте я думала, но так и не придумала, как лучше сделать, просто самой все вбивать ну это капец 

!!!Короче основная проблема в том, что локальную карту с обычной яндекс-картой нельзя объединить, можно только из той карты брать некоторые инструменты, например - вызов такси, создание маршрута по точкам и тд

Самые популярные маршруты, хм. Ну в бд тогда можно хранить все новые сгенеренные маршруты, чисто по списку точек. Но блин, это ведь их в перспективе гипер много может быть, мб вообще отказаться от идеи этой

 - объект маршрут - это умно, нам все равно нужно будет у пользователя их архивировать как-то
 - с пользователем тоже согласна, только список предпочтений мы кажется пока решили не брать в связи с и так небольшим кол-вом пар-ов
 - насчет анкеты вот несогласна, мне кажется это напрямую легче из визуалки в алгоритм доставать, дабы не запрашивать к бд лишний раз
 - хмхмхм, хорошо, это звучит несложно, так что попробую сделать

**Comment by KMn04** [comment]
Понял, тогда забудем про время работы и оценки

Мда, очень грустно, но видимо решать будет со временем и только гуглением

Я за то, чтоб отказаться от популярных и готовых маршрутов, у нас и так жизнь непростая намечается 

Тогда получается, у нас в бд прибавятся маршрут, пользователь и жалобы?
А насчёт анкеты предпочтений, это не фильтр по параметрам, это типа анкета, которую надо заполнить при регистрации, чтобы при составлении маршрута человеку, который любит парки, между парком и кино предложили в первую очередь парк, воть как-то так
Но звучит как-то сложновато, возможно, действительно лучше отказаться от идеи предпочтений, оставить только фильтр параметров
